-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "BetType" ADD VALUE 'TEAM_TOTAL_OVER_HOME';
ALTER TYPE "BetType" ADD VALUE 'TEAM_TOTAL_UNDER_HOME';
ALTER TYPE "BetType" ADD VALUE 'TEAM_TOTAL_OVER_AWAY';
ALTER TYPE "BetType" ADD VALUE 'TEAM_TOTAL_UNDER_AWAY';
ALTER TYPE "BetType" ADD VALUE 'QUARTER_WINNER_HOME';
ALTER TYPE "BetType" ADD VALUE 'QUARTER_WINNER_AWAY';
ALTER TYPE "BetType" ADD VALUE 'QUARTER_OVER';
ALTER TYPE "BetType" ADD VALUE 'QUARTER_UNDER';
ALTER TYPE "BetType" ADD VALUE 'TEAM_QUARTER_OVER_HOME';
ALTER TYPE "BetType" ADD VALUE 'TEAM_QUARTER_UNDER_HOME';
ALTER TYPE "BetType" ADD VALUE 'TEAM_QUARTER_OVER_AWAY';
ALTER TYPE "BetType" ADD VALUE 'TEAM_QUARTER_UNDER_AWAY';
ALTER TYPE "BetType" ADD VALUE 'FIRST_HALF_WINNER_HOME';
ALTER TYPE "BetType" ADD VALUE 'FIRST_HALF_WINNER_AWAY';
ALTER TYPE "BetType" ADD VALUE 'FIRST_HALF_OVER';
ALTER TYPE "BetType" ADD VALUE 'FIRST_HALF_UNDER';
ALTER TYPE "BetType" ADD VALUE 'SECOND_HALF_WINNER_HOME';
ALTER TYPE "BetType" ADD VALUE 'SECOND_HALF_WINNER_AWAY';
ALTER TYPE "BetType" ADD VALUE 'SECOND_HALF_OVER';
ALTER TYPE "BetType" ADD VALUE 'SECOND_HALF_UNDER';
ALTER TYPE "BetType" ADD VALUE 'OVERTIME_YES';
ALTER TYPE "BetType" ADD VALUE 'OVERTIME_NO';
ALTER TYPE "BetType" ADD VALUE 'HIGHEST_QUARTER';
ALTER TYPE "BetType" ADD VALUE 'ALL_QUARTERS_SAME_WINNER';

-- AlterTable
ALTER TABLE "bets" ADD COLUMN     "quarter" INTEGER,
ADD COLUMN     "teamSide" TEXT;

-- AlterTable
ALTER TABLE "games" ADD COLUMN     "awayOT1" INTEGER,
ADD COLUMN     "awayOT2" INTEGER,
ADD COLUMN     "awayOT3" INTEGER,
ADD COLUMN     "awayQ1" INTEGER,
ADD COLUMN     "awayQ2" INTEGER,
ADD COLUMN     "awayQ3" INTEGER,
ADD COLUMN     "awayQ4" INTEGER,
ADD COLUMN     "homeOT1" INTEGER,
ADD COLUMN     "homeOT2" INTEGER,
ADD COLUMN     "homeOT3" INTEGER,
ADD COLUMN     "homeQ1" INTEGER,
ADD COLUMN     "homeQ2" INTEGER,
ADD COLUMN     "homeQ3" INTEGER,
ADD COLUMN     "homeQ4" INTEGER,
ADD COLUMN     "period" INTEGER,
ADD COLUMN     "timeRemaining" TEXT;
